import Head from "next/head";

const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " | PDMS" : "PDMS"}</title>
        {/* <title>Purbani Document Management System</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ToastContainer position="bottom-center" limit={1} /> */}
      <main>{children}</main>
    </>
  );
};

export default Layout;
